In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle

In [2]:
df = pd.read_csv("../data/flood_dataset_clean.csv")

df.head()

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,DrainageSystems,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,InactiveDisasterPreparedness,FloodProbability
0,0,1,8,2,10,7,4,4,8,8,6,7,8,2,0.454329
1,8,10,9,10,10,4,9,1,4,1,0,2,5,1,0.592137
2,7,5,6,0,10,7,9,5,9,2,8,4,1,3,0.558937
3,4,10,4,3,10,6,8,8,4,2,10,1,4,0,0.521874
4,4,4,0,6,9,1,8,5,4,6,4,9,10,9,0.552644

In [3]:
df.columns

Index(['MonsoonIntensity', 'TopographyDrainage', 'RiverManagement',
       'Deforestation', 'Urbanization', 'ClimateChange', 'DamsQuality',
       'Siltation', 'DrainageSystems', 'Landslides', 'Watersheds',
       'DeterioratingInfrastructure', 'PopulationScore',
       'InactiveDisasterPreparedness', 'FloodProbability'],
      dtype='str')

In [4]:
median_value = df["FloodProbability"].median()

df["FloodRisk"] = df["FloodProbability"].apply(
    lambda x: 1 if x >= median_value else 0
)

df[["FloodProbability", "FloodRisk"]].head()

   FloodProbability  FloodRisk
0          0.454329          0
1          0.592137          1
2          0.558937          1
3          0.521874          1
4          0.552644          1

In [5]:
df["FloodRisk"].value_counts()

FloodRisk
0    25000
1    25000
Name: count, dtype: int64

In [6]:
X = df.drop(columns=["FloodProbability", "FloodRisk"])
y = df["FloodRisk"]

X.head()

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,DrainageSystems,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,InactiveDisasterPreparedness
0,0,1,8,2,10,7,4,4,8,8,6,7,8,2
1,8,10,9,10,10,4,9,1,4,1,0,2,5,1
2,7,5,6,0,10,7,9,5,9,2,8,4,1,3
3,4,10,4,3,10,6,8,8,4,2,10,1,4,0
4,4,4,0,6,9,1,8,5,4,6,4,9,10,9

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

X_train.shape, X_test.shape

((40000, 14), (10000, 14))

In [8]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [9]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X.columns)

X_train_scaled.head()

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,DrainageSystems,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,InactiveDisasterPreparedness
0,0.948606,0.633527,-0.319424,0.000276,0.314469,0.319906,-1.260056,1.269789,0.310226,1.580878,0.639105,0.317409,-0.315636,-0.633574
1,-0.628724,-0.632135,0.629689,-1.579223,-0.950142,0.636465,0.000962,-1.261499,1.256520,-0.311313,0.006101,-0.000716,0.316142,-1.264066
2,0.948606,-1.581381,-1.268536,0.000276,-0.633989,-0.946328,-0.314293,0.953378,-0.005205,-0.942043,-0.626904,-0.318841,0.000253,1.257903
3,-1.259656,0.949942,0.629689,0.632076,-0.317836,-0.946328,0.631471,-1.577909,1.256520,-0.311313,-1.576411,-1.591340,-0.947415,1.573149
4,0.948606,0.000696,0.313318,-0.947423,-1.582447,0.003348,-0.944802,-0.945088,0.941089,-0.942043,-0.310402,-0.000716,-1.579193,1.257903

In [10]:
X_train_scaled.to_csv("../data/X_train.csv", index=False)
X_test_scaled.to_csv("../data/X_test.csv", index=False)
y_train.to_csv("../data/y_train.csv", index=False)
y_test.to_csv("../data/y_test.csv", index=False)

with open("../models/scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

print("Preprocessing completed and files saved successfully.")

Preprocessing completed and files saved successfully.